# Generated by Django 2.1.2 on 2018-12-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_week', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_abbrev', models.CharField(max_length=100)),
                ('poinst_for', models.IntegerField()),
                ('opponent', models.CharField(max_length=100)),
                ('points_against', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PastSeasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('place', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('points_for', models.IntegerField()),
                ('points_against', models.IntegerField()),
            ],
        ),
    ]
