# Generated by Django 2.1.2 on 2019-01-22 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_week', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_abbrev', models.CharField(max_length=100)),
                ('poinst_for', models.FloatField()),
                ('opponent', models.CharField(max_length=100)),
                ('points_against', models.FloatField()),
                ('result', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PastSeasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('place', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('points_for', models.FloatField()),
                ('points_against', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pastseasons',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Player'),
        ),
        migrations.AddField(
            model_name='currentseason',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Player'),
        ),
    ]
