# Generated by Django 2.1.2 on 2018-12-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentseason',
            name='poinst_for',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='currentseason',
            name='points_against',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pastseasons',
            name='points_against',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pastseasons',
            name='points_for',
            field=models.FloatField(),
        ),
    ]
