# Generated by Django 2.2.2 on 2019-11-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('basic_app', '0002_auto_20191113_1708'), ('basic_app', '0003_player_player_id'), ('basic_app', '0004_currentseason_point_dif'), ('basic_app', '0005_auto_20191113_2153'), ('basic_app', '0006_auto_20191113_2339')]

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentseason',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Skittish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminated', models.BooleanField(default=False)),
                ('elim_score', models.FloatField(blank=True, null=True)),
                ('elim_week', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentseason',
            name='point_dif',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='currentseason',
            options={'ordering': ['-year', 'game_week']},
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('game_week', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_abbrev', models.CharField(max_length=100)),
                ('points_for', models.FloatField()),
                ('points_against', models.FloatField()),
                ('place', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Player')),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['game_week', 'place'],
            },
        ),
    ]
