# Generated by Django 2.1.2 on 2019-01-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_currentseason_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pastseasons',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Player'),
        ),
        migrations.AddField(
            model_name='currentseason',
            name='owner',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='basic_app.Player'),
        ),
    ]
