# Generated by Django 2.2.2 on 2019-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentseason',
            name='point_dif',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
