# Generated by Django 2.2.2 on 2019-11-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_currentseason_point_dif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentseason',
            options={'ordering': ['-year', 'game_week']},
        ),
        migrations.AlterModelOptions(
            name='rankings',
            options={'ordering': ['game_week', 'place']},
        ),
    ]
