# Generated by Django 2.2.2 on 2019-11-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20191113_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankings',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankings',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
